### ISSUE TITLE
Zjebałeś

### ISSUE THREAD

**Issue by ddziaduch** [bendykowski/codewars#1]
Wcięcia nie działają w https://github.com/bendykowski/codewars/blob/master/snail-sort/index.js przez co kod traci na czytelności

**Comment by lukasz-bendykowski-fluke** [comment]
@ddziaduch Co to znaczy, że wcięcia nie działają? 😛

**Comment by ddziaduch** [comment]
Brakuje ich 🙂
Pozdrawiam serdecznie.
———
Damian Dziaduch
Programista, bloger, internauta
https://damian.dziaduch.pl <https://damian.dziaduch.pl/>
damian@dziaduch.pl <mailto:damian@dziaduch.pl>

**Comment by lukasz-bendykowski-fluke** [comment]
![2019-09-09 09_50_53-codewars_index js](https://user-images.githubusercontent.com/40466851/64517144-a93aeb80-d2e7-11e9-9462-cf76c00bae5e.png)

Tych wcięć brakuje?

**Comment by ddziaduch** [comment]
Ciekawe sprawa, faktycznie są a nic nie zmieniłeś. Odświeżyłem tylko stronę. Coś mi przeglądarka popsuła 🤔
